server:
  port: 8080
  address: localhost

app:
  url:
    confirmationZoo: http://localhost:6060
    notificationZoo: http://localhost:6061

contacts:
  email: abc@gmail.com
  phone:
    number: 9658008080
  lat: 55.998564
  lng: 37.225150
  address: Moscow, Zelenograd

spring:
  h2:
    console:
      enabled: false
  datasource:
    password: ${PROD_POSTGRE_PASSWORD}
    username: ${PROD_POSTGRE_USERNAME}
    url: ${PROD_POSTGRE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  security:
    jwt:
      keystore-location: ${KEYSTORE_LOCATION}
      keystore-password: ${KEYSTORE_PASSWORD}
      key-alias: ${KEY_ALIAS}
      private-key-passphrase: ${PRIVATE_KEY_PASSPHRASE}

vk:
  app:
    id: ${VK_APP_ID}
  client:
    id: ${VK_CLIENT_ID}
  service:
    token: ${VK_SERVICE_TOKEN}
  owner:
    id: -198597086
  album:
    id: 276400572

map:
  api:
    key: ${YANDEX_MAP_API_KEY}

logging:
  file:
    name: logs/app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.nekromant.zoo: INFO
    org.hibernate: ERROR